### ISSUE TITLE
SSL system not working 

### ISSUE THREAD

**Issue by Gouravyadavyt** [santydesignscr/MOFHY-Multi-Language#1]
Bro recently I use your script .
All Good but SSL system is not working.
Please check it .

**Comment by santydesignscr** [comment]
Sorry for the late reply, this script is no loger maintained by the original creator, please consider using: https://github.com/mahtab2003/Xera

**Comment by santydesignscr** [comment]
Xera have multi language system
![image](https://user-images.githubusercontent.com/88201812/217715067-df4e6a70-1c13-4d96-89c8-4ce9ce42ac9f.png)
